version: '{build}'

skip_tags: true

install: []

environment:
  matrix:
    - VSVERSION: Visual Studio 10 2010
    - VSVERSION: Visual Studio 11 2012
    - VSVERSION: Visual Studio 12 2013
    - VSVERSION: Visual Studio 14 2015
    - VSVERSION: Visual Studio 15 2017
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

build_script:
  - md build
  - cd build
  - if "%PLATFORM%"=="x64" cmake -G "%VSVERSION% Win64" ../test
  - if "%PLATFORM%"=="Win32" cmake -G "%VSVERSION%" ../test
  - msbuild /m /p:Configuration="%CONFIGURATION%" /p:Platform="%PLATFORM%" process.sln
  - cd %CONFIGURATION%
  - utest_test.exe
